#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""从后端 pydantic CockpitVM / BUPageVM 同步 frontend/src/types/vm.ts 的字段清单区。

- 保留 vm.ts 手写类型与中文注释（GEN:BEGIN 之上 + 手写 export type 全文）。
- 仅维护 ``// --- GEN:BEGIN ---`` … ``// --- GEN:END ---`` 内的字段名常量，
  供契约抽查与 CI 防漂移。
- ``--check``：重新生成后与仓内文件 diff 非空 → exit 1（verify 闸）。

用法：
  .venv/bin/python scripts/gen_vm_ts.py
  .venv/bin/python scripts/gen_vm_ts.py --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
OUT = ROOT / "frontend" / "src" / "types" / "vm.ts"
BEGIN = "// --- GEN:BEGIN ---"
END = "// --- GEN:END ---"


def field_block() -> str:
    from viewmodels import BUPageVM, CockpitVM

    def keys(model) -> list[str]:
        return sorted(model.model_fields.keys())

    ck, bk = keys(CockpitVM), keys(BUPageVM)
    lines = [
        "// AUTO-GENERATED by scripts/gen_vm_ts.py — field names from pydantic model_fields",
        f"// CockpitVM: {len(ck)} fields; BUPageVM: {len(bk)} fields",
        "export const COCKPIT_VM_FIELDS = [",
        *[f'  "{k}",' for k in ck],
        "] as const",
        "",
        "export const BU_PAGE_VM_FIELDS = [",
        *[f'  "{k}",' for k in bk],
        "] as const",
        "",
        "export type CockpitVmField = (typeof COCKPIT_VM_FIELDS)[number]",
        "export type BuPageVmField = (typeof BU_PAGE_VM_FIELDS)[number]",
        "",
    ]
    return "\n".join(lines)


def splice(src: str, body: str) -> str:
    block = f"{BEGIN}\n{body.rstrip()}\n{END}\n"
    if BEGIN in src and END in src:
        pre = src.split(BEGIN)[0].rstrip() + "\n\n"
        post = src.split(END, 1)[1]
        # drop leading newlines from post
        post = post.lstrip("\n")
        if post and not post.startswith("\n"):
            post = "\n" + post if post else ""
        return pre + block + post
    # append gen block at end
    return src.rstrip() + "\n\n" + block


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    old = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
    body = field_block()
    new = splice(old, body)
    if args.check:
        if new != old:
            print("vm.ts GEN block drift — run: .venv/bin/python scripts/gen_vm_ts.py", file=sys.stderr)
            import difflib

            for line in list(
                difflib.unified_diff(old.splitlines(), new.splitlines(), lineterm="", n=0)
            )[:80]:
                print(line)
            return 1
        # also assert hand types mention each cockpit field loosely
        missing = []
        from viewmodels import CockpitVM

        for k in CockpitVM.model_fields:
            if k not in old and f'"{k}"' not in old:
                # field may only appear in GEN after first run
                if f'"{k}"' not in new:
                    missing.append(k)
        if missing:
            print("missing field names in vm.ts:", missing, file=sys.stderr)
            return 1
        print("vm.ts GEN block OK")
        return 0
    OUT.write_text(new, encoding="utf-8")
    print(f"wrote GEN block → {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
